### PR TITLE
Fix/brunswick green spider

### PR DESCRIPTION
**Pull request by trent-howard**
Update the Brunny Green spider to use their handy API.

They don't seem to list any price info anywhere, even after following different links on the gig page.

### Risks
I've set `ROBOTSTXT_OBEY = False`
There might be a better way around it, but the request is ignored if we respect their robots.txt
Maybe we could just make the API calls with Requests instead to differentiate it from the rest of the scraper requests.

Honestly, it's been a while since I've written any decent amount of python - lemme know if I did something dumb

### CODE REVIEW

**Comment by diabolical-ninja** [comment]
There's a bunch of DB entries with description "test". Presumably that's an artefact of the dev effort? Is it safe to delete these?
image

**Review by diabolical-ninja — APPROVED** [review]
LGTM

**Comment by trent-howard** [comment]
I dunno why I can't just reply to your comment... But yeah, I didn't actually realise they were being persisted. We can drop those.

**Comment by diabolical-ninja** [comment]
> I dunno why I can't just reply to your comment... But yeah, I didn't actually realise they were being persisted. We can drop those.

Done.

**Pull request merged**
